# automatically generated by the FlatBuffers compiler, do not modify

# namespace: schema

class Action(object):
    NONE = 0
    CatFeed = 1
    RatAttack = 2
    RatNap = 3
    RatCollision = 4
    PlaceDirt = 5
    BreakDirt = 6
    CheesePickup = 7
    CheeseSpawn = 8
    CatScratch = 9
    CatPounce = 10
    PlaceTrap = 11
    TriggerTrap = 12
    DamageAction = 13
    SpawnAction = 14
    DieAction = 15
    IndicatorStringAction = 16
    IndicatorDotAction = 17
    IndicatorLineAction = 18
