# automatically generated by the FlatBuffers compiler, do not modify

# namespace: schema

import flatbuffers
from flatbuffers.compat import import_numpy
from typing import Any
np = import_numpy()

# Create a Rat King at the specified location
class CreateRatKing(object):
    __slots__ = ['_tab']

    @classmethod
    def SizeOf(cls) -> int:
        return 2

    # CreateRatKing
    def Init(self, buf: bytes, pos: int):
        self._tab = flatbuffers.table.Table(buf, pos)

    # center square of the rat king
    # (all rats in the 3x3 square centered here get converted to the king)
    # CreateRatKing
    def Center(self): return self._tab.Get(flatbuffers.number_types.Uint16Flags, self._tab.Pos + flatbuffers.number_types.UOffsetTFlags.py_type(0))

def CreateCreateRatKing(builder, center):
    builder.Prep(2, 2)
    builder.PrependUint16(center)
    return builder.Offset()
