# automatically generated by the FlatBuffers compiler, do not modify

# namespace: schema

import flatbuffers
from flatbuffers.compat import import_numpy
from typing import Any
from ..schema.SpawnAction import SpawnAction
from typing import Optional
np = import_numpy()

# A list of initial bodies to be placed on the map.
class InitialBodyTable(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset: int = 0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = InitialBodyTable()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsInitialBodyTable(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # InitialBodyTable
    def Init(self, buf: bytes, pos: int):
        self._tab = flatbuffers.table.Table(buf, pos)

    # InitialBodyTable
    def SpawnActions(self, j: int) -> Optional[SpawnAction]:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            x = self._tab.Vector(o)
            x += flatbuffers.number_types.UOffsetTFlags.py_type(j) * 8
            obj = SpawnAction()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # InitialBodyTable
    def SpawnActionsLength(self) -> int:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # InitialBodyTable
    def SpawnActionsIsNone(self) -> bool:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        return o == 0

def InitialBodyTableStart(builder: flatbuffers.Builder):
    builder.StartObject(1)

def Start(builder: flatbuffers.Builder):
    InitialBodyTableStart(builder)

def InitialBodyTableAddSpawnActions(builder: flatbuffers.Builder, spawnActions: int):
    builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(spawnActions), 0)

def AddSpawnActions(builder: flatbuffers.Builder, spawnActions: int):
    InitialBodyTableAddSpawnActions(builder, spawnActions)

def InitialBodyTableStartSpawnActionsVector(builder, numElems: int) -> int:
    return builder.StartVector(8, numElems, 2)

def StartSpawnActionsVector(builder, numElems: int) -> int:
    return InitialBodyTableStartSpawnActionsVector(builder, numElems)

def InitialBodyTableEnd(builder: flatbuffers.Builder) -> int:
    return builder.EndObject()

def End(builder: flatbuffers.Builder) -> int:
    return InitialBodyTableEnd(builder)
