# automatically generated by the FlatBuffers compiler, do not modify

# namespace: schema

import flatbuffers
from flatbuffers.compat import import_numpy
from typing import Any
np = import_numpy()

# Happens when a rat tries to pick up cheese on a trap
class TriggerRatTrap(object):
    __slots__ = ['_tab']

    @classmethod
    def SizeOf(cls) -> int:
        return 4

    # TriggerRatTrap
    def Init(self, buf: bytes, pos: int):
        self._tab = flatbuffers.table.Table(buf, pos)

    # TriggerRatTrap
    def Loc(self): return self._tab.Get(flatbuffers.number_types.Uint16Flags, self._tab.Pos + flatbuffers.number_types.UOffsetTFlags.py_type(0))
    # TriggerRatTrap
    def Team(self): return self._tab.Get(flatbuffers.number_types.Int8Flags, self._tab.Pos + flatbuffers.number_types.UOffsetTFlags.py_type(2))

def CreateTriggerRatTrap(builder, loc, team):
    builder.Prep(2, 4)
    builder.Pad(1)
    builder.PrependInt8(team)
    builder.PrependUint16(loc)
    return builder.Offset()
