// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';

/**
 * Cat jump from start to end
 */
export class CatPounce {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):CatPounce {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

startLoc():number {
  return this.bb!.readUint16(this.bb_pos);
}

endLoc():number {
  return this.bb!.readUint16(this.bb_pos + 2);
}

static sizeOf():number {
  return 4;
}

static createCatPounce(builder:flatbuffers.Builder, startLoc: number, endLoc: number):flatbuffers.Offset {
  builder.prep(2, 4);
  builder.writeInt16(endLoc);
  builder.writeInt16(startLoc);
  return builder.offset();
}

}
