// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';

/**
 * Spawn a cheese at a location
 */
export class CheeseSpawn {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):CheeseSpawn {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

loc():number {
  return this.bb!.readUint16(this.bb_pos);
}

amount():number {
  return this.bb!.readUint16(this.bb_pos + 2);
}

static sizeOf():number {
  return 4;
}

static createCheeseSpawn(builder:flatbuffers.Builder, loc: number, amount: number):flatbuffers.Offset {
  builder.prep(2, 4);
  builder.writeInt16(amount);
  builder.writeInt16(loc);
  return builder.offset();
}

}
