// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';

/**
 * Create a Rat King at the specified location
 */
export class CreateRatKing {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):CreateRatKing {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

/**
 * center square of the rat king
 * (all rats in the 3x3 square centered here get converted to the king)
 */
center():number {
  return this.bb!.readUint16(this.bb_pos);
}

static sizeOf():number {
  return 2;
}

static createCreateRatKing(builder:flatbuffers.Builder, center: number):flatbuffers.Offset {
  builder.prep(2, 2);
  builder.writeInt16(center);
  return builder.offset();
}

}
