// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';

import { SpawnAction } from '../../battlecode/schema/spawn-action';


/**
 * A list of initial bodies to be placed on the map.
 */
export class InitialBodyTable {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):InitialBodyTable {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsInitialBodyTable(bb:flatbuffers.ByteBuffer, obj?:InitialBodyTable):InitialBodyTable {
  return (obj || new InitialBodyTable()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsInitialBodyTable(bb:flatbuffers.ByteBuffer, obj?:InitialBodyTable):InitialBodyTable {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new InitialBodyTable()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

spawnActions(index: number, obj?:SpawnAction):SpawnAction|null {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? (obj || new SpawnAction()).__init(this.bb!.__vector(this.bb_pos + offset) + index * 8, this.bb!) : null;
}

spawnActionsLength():number {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.__vector_len(this.bb_pos + offset) : 0;
}

static startInitialBodyTable(builder:flatbuffers.Builder) {
  builder.startObject(1);
}

static addSpawnActions(builder:flatbuffers.Builder, spawnActionsOffset:flatbuffers.Offset) {
  builder.addFieldOffset(0, spawnActionsOffset, 0);
}

static startSpawnActionsVector(builder:flatbuffers.Builder, numElems:number) {
  builder.startVector(8, numElems, 2);
}

static endInitialBodyTable(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static createInitialBodyTable(builder:flatbuffers.Builder, spawnActionsOffset:flatbuffers.Offset):flatbuffers.Offset {
  InitialBodyTable.startInitialBodyTable(builder);
  InitialBodyTable.addSpawnActions(builder, spawnActionsOffset);
  return InitialBodyTable.endInitialBodyTable(builder);
}
}
