// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

export enum RobotType {
  NONE = 0,
  RAT = 1,
  RAT_KING = 2,
  CAT = 3
}
