// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';

/**
 * Upgrade a 3x3 area of rats into a rat king
 */
export class UpgradeToRatKing {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):UpgradeToRatKing {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

/**
 * Placeholder data bc the struct cant be empty
 */
phantom():number {
  return this.bb!.readUint16(this.bb_pos);
}

static sizeOf():number {
  return 2;
}

static createUpgradeToRatKing(builder:flatbuffers.Builder, phantom: number):flatbuffers.Offset {
  builder.prep(2, 2);
  builder.writeInt16(phantom);
  return builder.offset();
}

}
