// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

export enum WinType {
  RESIGNATION = 0,
  RATKING_DESTROYED = 1,
  BACKSTAB_RATKING_DESTROYED = 2,
  MORE_POINTS = 3,
  TIE = 4,
  COIN_FLIP = 5
}
