"use strict";
// automatically generated by the FlatBuffers compiler, do not modify
Object.defineProperty(exports, "__esModule", { value: true });
exports.BreakDirt = void 0;
/**
 * Indicate that a dirt wall is destroyed
 */
var BreakDirt = /** @class */ (function () {
    function BreakDirt() {
        this.bb = null;
        this.bb_pos = 0;
    }
    BreakDirt.prototype.__init = function (i, bb) {
        this.bb_pos = i;
        this.bb = bb;
        return this;
    };
    BreakDirt.prototype.loc = function () {
        return this.bb.readUint16(this.bb_pos);
    };
    BreakDirt.sizeOf = function () {
        return 2;
    };
    BreakDirt.createBreakDirt = function (builder, loc) {
        builder.prep(2, 2);
        builder.writeInt16(loc);
        return builder.offset();
    };
    return BreakDirt;
}());
exports.BreakDirt = BreakDirt;
