"use strict";
// automatically generated by the FlatBuffers compiler, do not modify
Object.defineProperty(exports, "__esModule", { value: true });
exports.CatFeed = void 0;
/**
 * Cat feeds on a rat
 */
var CatFeed = /** @class */ (function () {
    function CatFeed() {
        this.bb = null;
        this.bb_pos = 0;
    }
    CatFeed.prototype.__init = function (i, bb) {
        this.bb_pos = i;
        this.bb = bb;
        return this;
    };
    /**
     * the ID of the eaten rat
     */
    CatFeed.prototype.id = function () {
        return this.bb.readUint16(this.bb_pos);
    };
    CatFeed.sizeOf = function () {
        return 2;
    };
    CatFeed.createCatFeed = function (builder, id) {
        builder.prep(2, 2);
        builder.writeInt16(id);
        return builder.offset();
    };
    return CatFeed;
}());
exports.CatFeed = CatFeed;
