"use strict";
// automatically generated by the FlatBuffers compiler, do not modify
Object.defineProperty(exports, "__esModule", { value: true });
exports.CatPounce = void 0;
/**
 * Cat jump from start to end
 */
var CatPounce = /** @class */ (function () {
    function CatPounce() {
        this.bb = null;
        this.bb_pos = 0;
    }
    CatPounce.prototype.__init = function (i, bb) {
        this.bb_pos = i;
        this.bb = bb;
        return this;
    };
    CatPounce.prototype.startLoc = function () {
        return this.bb.readUint16(this.bb_pos);
    };
    CatPounce.prototype.endLoc = function () {
        return this.bb.readUint16(this.bb_pos + 2);
    };
    CatPounce.sizeOf = function () {
        return 4;
    };
    CatPounce.createCatPounce = function (builder, startLoc, endLoc) {
        builder.prep(2, 4);
        builder.writeInt16(endLoc);
        builder.writeInt16(startLoc);
        return builder.offset();
    };
    return CatPounce;
}());
exports.CatPounce = CatPounce;
