"use strict";
// automatically generated by the FlatBuffers compiler, do not modify
Object.defineProperty(exports, "__esModule", { value: true });
exports.CatScratch = void 0;
/**
 * Cat scratch at location
 */
var CatScratch = /** @class */ (function () {
    function CatScratch() {
        this.bb = null;
        this.bb_pos = 0;
    }
    CatScratch.prototype.__init = function (i, bb) {
        this.bb_pos = i;
        this.bb = bb;
        return this;
    };
    CatScratch.prototype.loc = function () {
        return this.bb.readUint16(this.bb_pos);
    };
    CatScratch.sizeOf = function () {
        return 2;
    };
    CatScratch.createCatScratch = function (builder, loc) {
        builder.prep(2, 2);
        builder.writeInt16(loc);
        return builder.offset();
    };
    return CatScratch;
}());
exports.CatScratch = CatScratch;
