"use strict";
// automatically generated by the FlatBuffers compiler, do not modify
Object.defineProperty(exports, "__esModule", { value: true });
exports.CheeseSpawn = void 0;
/**
 * Spawn a cheese at a location
 */
var CheeseSpawn = /** @class */ (function () {
    function CheeseSpawn() {
        this.bb = null;
        this.bb_pos = 0;
    }
    CheeseSpawn.prototype.__init = function (i, bb) {
        this.bb_pos = i;
        this.bb = bb;
        return this;
    };
    CheeseSpawn.prototype.loc = function () {
        return this.bb.readUint16(this.bb_pos);
    };
    CheeseSpawn.prototype.amount = function () {
        return this.bb.readUint16(this.bb_pos + 2);
    };
    CheeseSpawn.sizeOf = function () {
        return 4;
    };
    CheeseSpawn.createCheeseSpawn = function (builder, loc, amount) {
        builder.prep(2, 4);
        builder.writeInt16(amount);
        builder.writeInt16(loc);
        return builder.offset();
    };
    return CheeseSpawn;
}());
exports.CheeseSpawn = CheeseSpawn;
