"use strict";
// automatically generated by the FlatBuffers compiler, do not modify
Object.defineProperty(exports, "__esModule", { value: true });
exports.CheesePickup = void 0;
/**
 * Indicate that a cheese has been picked up from the map by a rat
 */
var CheesePickup = /** @class */ (function () {
    function CheesePickup() {
        this.bb = null;
        this.bb_pos = 0;
    }
    CheesePickup.prototype.__init = function (i, bb) {
        this.bb_pos = i;
        this.bb = bb;
        return this;
    };
    CheesePickup.prototype.loc = function () {
        return this.bb.readUint16(this.bb_pos);
    };
    CheesePickup.sizeOf = function () {
        return 2;
    };
    CheesePickup.createCheesePickup = function (builder, loc) {
        builder.prep(2, 2);
        builder.writeInt16(loc);
        return builder.offset();
    };
    return CheesePickup;
}());
exports.CheesePickup = CheesePickup;
