"use strict";
// automatically generated by the FlatBuffers compiler, do not modify
Object.defineProperty(exports, "__esModule", { value: true });
exports.PlaceDirt = void 0;
/**
 * Indicate that a dirt wall is placed
 */
var PlaceDirt = /** @class */ (function () {
    function PlaceDirt() {
        this.bb = null;
        this.bb_pos = 0;
    }
    PlaceDirt.prototype.__init = function (i, bb) {
        this.bb_pos = i;
        this.bb = bb;
        return this;
    };
    PlaceDirt.prototype.loc = function () {
        return this.bb.readUint16(this.bb_pos);
    };
    PlaceDirt.sizeOf = function () {
        return 2;
    };
    PlaceDirt.createPlaceDirt = function (builder, loc) {
        builder.prep(2, 2);
        builder.writeInt16(loc);
        return builder.offset();
    };
    return PlaceDirt;
}());
exports.PlaceDirt = PlaceDirt;
