"use strict";
// automatically generated by the FlatBuffers compiler, do not modify
Object.defineProperty(exports, "__esModule", { value: true });
exports.RatAttack = void 0;
/**
 * Rat attacks another rat
 */
var RatAttack = /** @class */ (function () {
    function RatAttack() {
        this.bb = null;
        this.bb_pos = 0;
    }
    RatAttack.prototype.__init = function (i, bb) {
        this.bb_pos = i;
        this.bb = bb;
        return this;
    };
    /**
     * Id of the attacked rat
     */
    RatAttack.prototype.id = function () {
        return this.bb.readUint16(this.bb_pos);
    };
    RatAttack.sizeOf = function () {
        return 2;
    };
    RatAttack.createRatAttack = function (builder, id) {
        builder.prep(2, 2);
        builder.writeInt16(id);
        return builder.offset();
    };
    return RatAttack;
}());
exports.RatAttack = RatAttack;
