"use strict";
// automatically generated by the FlatBuffers compiler, do not modify
Object.defineProperty(exports, "__esModule", { value: true });
exports.RatSqueak = void 0;
/**
 * Rat squeak action
 */
var RatSqueak = /** @class */ (function () {
    function RatSqueak() {
        this.bb = null;
        this.bb_pos = 0;
    }
    RatSqueak.prototype.__init = function (i, bb) {
        this.bb_pos = i;
        this.bb = bb;
        return this;
    };
    RatSqueak.prototype.loc = function () {
        return this.bb.readUint16(this.bb_pos);
    };
    RatSqueak.sizeOf = function () {
        return 2;
    };
    RatSqueak.createRatSqueak = function (builder, loc) {
        builder.prep(2, 2);
        builder.writeInt16(loc);
        return builder.offset();
    };
    return RatSqueak;
}());
exports.RatSqueak = RatSqueak;
