"use strict";
// automatically generated by the FlatBuffers compiler, do not modify
Object.defineProperty(exports, "__esModule", { value: true });
exports.RatNap = void 0;
/**
 * Kidnap a rat
 */
var RatNap = /** @class */ (function () {
    function RatNap() {
        this.bb = null;
        this.bb_pos = 0;
    }
    RatNap.prototype.__init = function (i, bb) {
        this.bb_pos = i;
        this.bb = bb;
        return this;
    };
    /**
     * Id of the napping victim
     */
    RatNap.prototype.id = function () {
        return this.bb.readUint16(this.bb_pos);
    };
    RatNap.sizeOf = function () {
        return 2;
    };
    RatNap.createRatNap = function (builder, id) {
        builder.prep(2, 2);
        builder.writeInt16(id);
        return builder.offset();
    };
    return RatNap;
}());
exports.RatNap = RatNap;
