"use strict";
// automatically generated by the FlatBuffers compiler, do not modify
Object.defineProperty(exports, "__esModule", { value: true });
exports.RobotType = void 0;
/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */
var RobotType;
(function (RobotType) {
    RobotType[RobotType["NONE"] = 0] = "NONE";
    RobotType[RobotType["RAT"] = 1] = "RAT";
    RobotType[RobotType["RAT_KING"] = 2] = "RAT_KING";
    RobotType[RobotType["CAT"] = 3] = "CAT";
})(RobotType || (exports.RobotType = RobotType = {}));
