"use strict";
// automatically generated by the FlatBuffers compiler, do not modify
Object.defineProperty(exports, "__esModule", { value: true });
exports.ThrowRat = void 0;
/**
 * Throw a rat
 */
var ThrowRat = /** @class */ (function () {
    function ThrowRat() {
        this.bb = null;
        this.bb_pos = 0;
    }
    ThrowRat.prototype.__init = function (i, bb) {
        this.bb_pos = i;
        this.bb = bb;
        return this;
    };
    /**
     * Id of the thrown rat
     */
    ThrowRat.prototype.id = function () {
        return this.bb.readUint16(this.bb_pos);
    };
    ThrowRat.prototype.loc = function () {
        return this.bb.readUint16(this.bb_pos + 2);
    };
    ThrowRat.sizeOf = function () {
        return 4;
    };
    ThrowRat.createThrowRat = function (builder, id, loc) {
        builder.prep(2, 4);
        builder.writeInt16(loc);
        builder.writeInt16(id);
        return builder.offset();
    };
    return ThrowRat;
}());
exports.ThrowRat = ThrowRat;
