"use strict";
// automatically generated by the FlatBuffers compiler, do not modify
Object.defineProperty(exports, "__esModule", { value: true });
exports.TrapType = void 0;
/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */
var TrapType;
(function (TrapType) {
    TrapType[TrapType["RAT_TRAP"] = 0] = "RAT_TRAP";
    TrapType[TrapType["CAT_TRAP"] = 1] = "CAT_TRAP";
})(TrapType || (exports.TrapType = TrapType = {}));
