"use strict";
// automatically generated by the FlatBuffers compiler, do not modify
Object.defineProperty(exports, "__esModule", { value: true });
exports.TriggerTrap = void 0;
/**
 * Triggers the trap
 */
var TriggerTrap = /** @class */ (function () {
    function TriggerTrap() {
        this.bb = null;
        this.bb_pos = 0;
    }
    TriggerTrap.prototype.__init = function (i, bb) {
        this.bb_pos = i;
        this.bb = bb;
        return this;
    };
    TriggerTrap.prototype.loc = function () {
        return this.bb.readUint16(this.bb_pos);
    };
    TriggerTrap.prototype.team = function () {
        return this.bb.readInt8(this.bb_pos + 2);
    };
    TriggerTrap.sizeOf = function () {
        return 4;
    };
    TriggerTrap.createTriggerTrap = function (builder, loc, team) {
        builder.prep(2, 4);
        builder.pad(1);
        builder.writeInt8(team);
        builder.writeInt16(loc);
        return builder.offset();
    };
    return TriggerTrap;
}());
exports.TriggerTrap = TriggerTrap;
