"use strict";
// automatically generated by the FlatBuffers compiler, do not modify
Object.defineProperty(exports, "__esModule", { value: true });
exports.WinType = void 0;
/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */
var WinType;
(function (WinType) {
    WinType[WinType["RESIGNATION"] = 0] = "RESIGNATION";
    WinType[WinType["RATKING_DESTROYED"] = 1] = "RATKING_DESTROYED";
    WinType[WinType["BACKSTAB_RATKING_DESTROYED"] = 2] = "BACKSTAB_RATKING_DESTROYED";
    WinType[WinType["MORE_POINTS"] = 3] = "MORE_POINTS";
    WinType[WinType["MORE_ROBOTS"] = 4] = "MORE_ROBOTS";
    WinType[WinType["MORE_CHEESE"] = 5] = "MORE_CHEESE";
    WinType[WinType["TIE"] = 6] = "TIE";
    WinType[WinType["COIN_FLIP"] = 7] = "COIN_FLIP";
})(WinType || (exports.WinType = WinType = {}));
